### PR TITLE
Remove attack pattern ID from name attribute

### PR DESCRIPTION
**Pull request by SYNchroACK**

### CODE REVIEW

**Comment by adulau** [comment]
Not sure about this one as it's super convenient to have the technique ID in the field.

**Comment by SYNchroACK** [comment]
> Not sure about this one as it's super convenient to have the technique ID in the field.

Yup, I totally understand the convenience. ;)

**Problem analysis (in my perspective):**
1. The issue is the mixing of a name with an attack pattern ID... down the road it will force someone to parse it, etc...
2. In other perspective, if there was an additional field in attack-pattern to put the ID (`Txxxx.yyy`), I think we would not have to think about this issue.

**Possible solution (in my perspective):**
1. I would keep the name field clear for the reason explained above
2. Add an additional custom field `x_mitre_external_id`, following the "pattern" of MITRE data source, even though we can see on the snippet (in the end of this message) that this `external_id` already exists in `external_references` (not easy accessible due the list).
3. Would talk with MITRE folks responsible for the JSON datasets and ask them about the possible to change/add the field mentioned on the previous point.
```
enterprise: https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack.json
mobile_attack: https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/mobile-attack/mobile-attack.json
ics_attack: https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/ics-attack/ics-attack.json
capec: https://raw.githubusercontent.com/mitre/cti/master/capec/2.1/stix-capec.json
```

**Snippet (`T1055.011`)**
```
{
    "id": "attack-pattern--0042a9f5-f053-4769-b3ef-9ad018dfa298",
    "name": "Extra Window Memory Injection",
    "type": "attack-pattern",
    "created": "2020-01-14T17:18:32.126Z",
    "modified": "2022-04-25T14:00:00.188Z",
    "x_mitre_is_subtechnique": true,
    "x_mitre_version": "1.0",
    "x_mitre_data_sources": [
        "Process: OS API Execution"
    ],
    "x_mitre_platforms": [
        "Windows"
    ],
    "x_mitre_domains": [
        "enterprise-attack"
    ],
    "external_references": [
        {
            "source_name": "mitre-attack",
            "external_id": "T1055.011",
            "url": "https://attack.mitre.org/techniques/T1055/011"
        },
        
        ...

    ],
    
    ...
    
},
```

**Comment by SYNchroACK** [comment]
ping @adulau @chrisr3d

**Comment by adulau** [comment]
Thank you! Sorry it took sometime, we reviewed all the different ingestion processes and for MISP export, it's all fine. Thank you for the contribution.

**Pull request merged**
